yunying:
  datasource:
    url: jdbc:mysql://localhost:3306/yunying?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 20040217
    driver-class-name: com.mysql.cj.jdbc.Driver
  zookeeper:
    connect-string: localhost:2181

